// <auto-generated />
namespace MusicStoreCodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_istrending : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_istrending));
        
        string IMigrationMetadata.Id
        {
            get { return "201702191221431_added_istrending"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
